name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install project dependencies
        run: uv sync --all-extras --group dev --group test
      - name: Check formatting with ruff
        run: uv run ruff format --check --diff .
      - name: Lint code with ruff
        run: uv run ruff check .
      - name: Run tests with pytest
        run: uv run pytest --cov ./ --junitxml=test-report.xml
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.xml
      - name: Publish test results
        uses: dorny/test-reporter@v1
        with:
          name: Unit Tests
          path: test-report.xml
          reporter: java-junit
  docker-build:
    name: Test Dockerfile build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Regenerate uv.lock if pyproject.toml changed
        run: uv lock
      - name: Commit updated uv.lock if needed
        if: startsWith(github.head_ref, 'release-please--')
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add uv.lock
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update uv.lock after version bump"
            git pull --rebase origin ${{ github.head_ref }}
            git push origin HEAD:${{ github.head_ref }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: test-image:ci
